"""
Report Generation Engine
Create professional PDF reports with charts and data
"""
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak, Image
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import pandas as pd
from datetime import datetime
import io
import os
import logging
from typing import Dict, List, Any, Optional

logger = logging.getLogger(__name__)

class PDFReportGenerator:
    """Generate professional PDF reports"""
    
    def __init__(self, title: str = "Analytics Report", author: str = "NISR Data Platform"):
        self.title = title
        self.author = author
        self.styles = getSampleStyleSheet()
        self.elements = []
        
        # Custom styles
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a73e8'),
            spaceAfter=30,
            alignment=TA_CENTER
        )
        
        self.heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#333333'),
            spaceAfter=12,
            spaceBefore=12
        )
        
        self.subheading_style = ParagraphStyle(
            'CustomSubHeading',
            parent=self.styles['Heading3'],
            fontSize=12,
            textColor=colors.HexColor('#666666'),
            spaceAfter=8
        )
    
    def add_title_page(self, subtitle: Optional[str] = None):
        """Add title page"""
        self.elements.append(Spacer(1, 2*inch))
        self.elements.append(Paragraph(self.title, self.title_style))
        
        if subtitle:
            subtitle_style = ParagraphStyle(
                'Subtitle',
                parent=self.styles['Normal'],
                fontSize=14,
                textColor=colors.HexColor('#666666'),
                alignment=TA_CENTER,
                spaceAfter=20
            )
            self.elements.append(Paragraph(subtitle, subtitle_style))
        
        # Add metadata
        meta_style = ParagraphStyle(
            'Meta',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#999999'),
            alignment=TA_CENTER
        )
        
        self.elements.append(Spacer(1, 1*inch))
        self.elements.append(Paragraph(f"Generated by: {self.author}", meta_style))
        self.elements.append(Paragraph(
            f"Date: {datetime.now().strftime('%B %d, %Y at %H:%M')}",
            meta_style
        ))
        
        self.elements.append(PageBreak())
    
    def add_section(self, title: str, level: int = 1):
        """Add section heading"""
        if level == 1:
            self.elements.append(Paragraph(title, self.heading_style))
        else:
            self.elements.append(Paragraph(title, self.subheading_style))
    
    def add_paragraph(self, text: str):
        """Add text paragraph"""
        self.elements.append(Paragraph(text, self.styles['Normal']))
        self.elements.append(Spacer(1, 0.2*inch))
    
    def add_bullet_list(self, items: List[str]):
        """Add bullet point list"""
        bullet_style = ParagraphStyle(
            'Bullet',
            parent=self.styles['Normal'],
            leftIndent=20,
            bulletIndent=10
        )
        
        for item in items:
            self.elements.append(Paragraph(f"• {item}", bullet_style))
        
        self.elements.append(Spacer(1, 0.2*inch))
    
    def add_table(self, data: pd.DataFrame, max_rows: int = 20):
        """Add data table"""
        # Limit rows if too many
        if len(data) > max_rows:
            table_data = data.head(max_rows)
            truncated = True
        else:
            table_data = data
            truncated = False
        
        # Prepare table data
        table_values = [table_data.columns.tolist()]
        for _, row in table_data.iterrows():
            table_values.append([str(val)[:50] for val in row.values])  # Limit cell width
        
        # Create table
        table = Table(table_values)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a73e8')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5f5f5')])
        ]))
        
        self.elements.append(table)
        
        if truncated:
            note_style = ParagraphStyle(
                'Note',
                parent=self.styles['Normal'],
                fontSize=8,
                textColor=colors.HexColor('#999999'),
                italic=True
            )
            self.elements.append(Spacer(1, 0.1*inch))
            self.elements.append(
                Paragraph(f"Note: Showing first {max_rows} of {len(data)} rows", note_style)
            )
        
        self.elements.append(Spacer(1, 0.3*inch))
    
    def add_statistics_table(self, stats: Dict[str, Any]):
        """Add key-value statistics table"""
        table_data = [[key, str(value)] for key, value in stats.items()]
        
        table = Table(table_data, colWidths=[3*inch, 2*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f0')),
            ('ALIGN', (0, 0), (0, -1), 'LEFT'),
            ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
            ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.white, colors.HexColor('#f9f9f9')])
        ]))
        
        self.elements.append(table)
        self.elements.append(Spacer(1, 0.3*inch))
    
    def add_chart_image(self, image_path: str, width: float = 5*inch):
        """Add chart image"""
        if os.path.exists(image_path):
            img = Image(image_path, width=width, height=width*0.6)
            self.elements.append(img)
            self.elements.append(Spacer(1, 0.3*inch))
        else:
            logger.warning(f"Chart image not found: {image_path}")
    
    def add_metrics_grid(self, metrics: Dict[str, float]):
        """Add metrics in a grid layout"""
        # Create 2-column grid
        items = list(metrics.items())
        table_data = []
        
        for i in range(0, len(items), 2):
            row = []
            for j in range(2):
                if i + j < len(items):
                    key, value = items[i + j]
                    if isinstance(value, float):
                        row.append(f"{key}\n{value:.4f}")
                    else:
                        row.append(f"{key}\n{value}")
                else:
                    row.append("")
            table_data.append(row)
        
        table = Table(table_data, colWidths=[3*inch, 3*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#e8f4f8')),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 2, colors.HexColor('#1a73e8')),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 20),
            ('TOPPADDING', (0, 0), (-1, -1), 20),
        ]))
        
        self.elements.append(table)
        self.elements.append(Spacer(1, 0.3*inch))
    
    def add_page_break(self):
        """Add page break"""
        self.elements.append(PageBreak())
    
    def generate(self, output_path: str) -> str:
        """Generate PDF file"""
        try:
            doc = SimpleDocTemplate(
                output_path,
                pagesize=letter,
                rightMargin=0.75*inch,
                leftMargin=0.75*inch,
                topMargin=0.75*inch,
                bottomMargin=0.75*inch
            )
            
            doc.build(self.elements)
            logger.info(f"PDF report generated: {output_path}")
            return output_path
            
        except Exception as e:
            logger.error(f"PDF generation failed: {e}")
            raise
    
    def generate_bytes(self) -> bytes:
        """Generate PDF as bytes for download"""
        try:
            buffer = io.BytesIO()
            doc = SimpleDocTemplate(
                buffer,
                pagesize=letter,
                rightMargin=0.75*inch,
                leftMargin=0.75*inch,
                topMargin=0.75*inch,
                bottomMargin=0.75*inch
            )
            
            doc.build(self.elements)
            buffer.seek(0)
            return buffer.getvalue()
            
        except Exception as e:
            logger.error(f"PDF bytes generation failed: {e}")
            raise


class DataExporter:
    """Export data in various formats"""
    
    @staticmethod
    def to_csv(df: pd.DataFrame, output_path: Optional[str] = None) -> bytes:
        """Export to CSV"""
        if output_path:
            df.to_csv(output_path, index=False)
            with open(output_path, 'rb') as f:
                return f.read()
        else:
            buffer = io.StringIO()
            df.to_csv(buffer, index=False)
            return buffer.getvalue().encode('utf-8')
    
    @staticmethod
    def to_excel(df: pd.DataFrame, output_path: Optional[str] = None, sheet_name: str = "Data") -> bytes:
        """Export to Excel"""
        if output_path:
            df.to_excel(output_path, sheet_name=sheet_name, index=False, engine='openpyxl')
            with open(output_path, 'rb') as f:
                return f.read()
        else:
            buffer = io.BytesIO()
            df.to_excel(buffer, sheet_name=sheet_name, index=False, engine='openpyxl')
            buffer.seek(0)
            return buffer.getvalue()
    
    @staticmethod
    def to_json(df: pd.DataFrame) -> str:
        """Export to JSON"""
        return df.to_json(orient='records', indent=2)


def create_analysis_report(
    title: str,
    dataset_name: str,
    analysis_results: Dict[str, Any],
    include_data: bool = True
) -> bytes:
    """Create a complete analysis report"""
    
    report = PDFReportGenerator(title=title)
    
    # Title page
    report.add_title_page(subtitle=f"Dataset: {dataset_name}")
    
    # Executive Summary
    report.add_section("Executive Summary")
    report.add_paragraph(
        f"This report provides a comprehensive analysis of the '{dataset_name}' dataset. "
        f"Generated on {datetime.now().strftime('%B %d, %Y')}."
    )
    
    # Dataset Overview
    if 'dataset_info' in analysis_results:
        info = analysis_results['dataset_info']
        report.add_section("Dataset Overview")
        report.add_statistics_table({
            "Number of Rows": info.get('num_rows', 'N/A'),
            "Number of Columns": info.get('num_columns', 'N/A'),
            "File Size": info.get('file_size', 'N/A'),
            "Upload Date": info.get('upload_date', 'N/A')
        })
    
    # Analysis Results
    if 'metrics' in analysis_results:
        report.add_section("Key Metrics")
        report.add_metrics_grid(analysis_results['metrics'])
    
    # Data Preview
    if include_data and 'data' in analysis_results:
        report.add_section("Data Preview")
        df = pd.DataFrame(analysis_results['data'])
        report.add_table(df, max_rows=15)
    
    # Statistics
    if 'statistics' in analysis_results:
        report.add_section("Statistical Summary")
        stats_df = pd.DataFrame(analysis_results['statistics'])
        report.add_table(stats_df)
    
    # Insights
    if 'insights' in analysis_results:
        report.add_section("Key Insights")
        report.add_bullet_list(analysis_results['insights'])
    
    return report.generate_bytes()
